"""Adding cascade deletion on orders

Revision ID: ea3f72ac8f16
Revises: 8997d3fadbde
Create Date: 2024-10-05 17:51:45.631270

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ea3f72ac8f16"
down_revision: Union[str, None] = "8997d3fadbde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "order_product_association_order_id_fkey",
        "order_product_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "order_product_association",
        "Orders",
        ["order_id"],
        ["order_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_product_association", type_="foreignkey")
    op.create_foreign_key(
        "order_product_association_order_id_fkey",
        "order_product_association",
        "Orders",
        ["order_id"],
        ["order_id"],
    )
    # ### end Alembic commands ###
