"""Adding username to user

Revision ID: 42f13ff5b2aa
Revises: 59f55493d64d
Create Date: 2024-09-14 02:24:11.472094

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42f13ff5b2aa"
down_revision: Union[str, None] = "59f55493d64d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("username", sa.String(), nullable=False))
    op.drop_column("user", "user")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("user", "username")
    # ### end Alembic commands ###
