"""Adding Order and OrderAssociation tables

Revision ID: 10dfe044e946
Revises: 0dd0e57f106c
Create Date: 2024-10-05 04:12:28.121783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10dfe044e946"
down_revision: Union[str, None] = "0dd0e57f106c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Orders",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index(op.f("ix_Orders_category"), "Orders", ["category"], unique=False)
    op.create_table(
        "order_product_association",
        sa.Column("order_product_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["Orders.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["Products.product_id"],
        ),
        sa.PrimaryKeyConstraint("order_product_id"),
        sa.UniqueConstraint("order_id", "product_id", name="idx_unique_order_product"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_product_association")
    op.drop_index(op.f("ix_Orders_category"), table_name="Orders")
    op.drop_table("Orders")
    # ### end Alembic commands ###
