"""Adding hybrid property and expression

Revision ID: 8997d3fadbde
Revises: ca8516ed6972
Create Date: 2024-10-05 17:32:41.527510

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "8997d3fadbde"
down_revision: Union[str, None] = "ca8516ed6972"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
