"""Adding username to user

Revision ID: 59f55493d64d
Revises: 7607beae617c
Create Date: 2024-09-14 02:21:03.435123

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59f55493d64d"
down_revision: Union[str, None] = "7607beae617c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("user", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "user")
    # ### end Alembic commands ###
