"""Removing category from Order

Revision ID: 48e5f774d7d0
Revises: 10dfe044e946
Create Date: 2024-10-05 04:37:38.263842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48e5f774d7d0"
down_revision: Union[str, None] = "10dfe044e946"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_Orders_category", table_name="Orders")
    op.drop_column("Orders", "total_price")
    op.drop_column("Orders", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Orders",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "Orders",
        sa.Column(
            "total_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index("ix_Orders_category", "Orders", ["category"], unique=False)
    # ### end Alembic commands ###
