"""Removing user order relationship for the first time

Revision ID: 10115cad7dbf
Revises: 48e5f774d7d0
Create Date: 2024-10-05 16:59:46.540453

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "10115cad7dbf"
down_revision: Union[str, None] = "48e5f774d7d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
