"""Adding user-orders relationship

Revision ID: ef2c53b6d928
Revises: ea3f72ac8f16
Create Date: 2024-10-05 18:27:30.481165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics

# revision identifiers, used by Alembic.
revision: str = "ef2c53b6d928"
down_revision: Union[str, None] = "ea3f72ac8f16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Orders",
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True
        ),
    )
    op.create_foreign_key(
        None, "Orders", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Orders", type_="foreignkey")
    op.drop_column("Orders", "user_id")
    # ### end Alembic commands ###
