"""Adding ProductTranslations model

Revision ID: b4c0e91d4d6d
Revises: 9700dbc803df
Create Date: 2024-10-17 03:45:33.550832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4c0e91d4d6d"
down_revision: Union[str, None] = "9700dbc803df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ProductTranslations",
        sa.Column("translation_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("language_code", sa.String(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["Products.product_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("translation_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ProductTranslations")
    # ### end Alembic commands ###
