"""Adding ProductTranslations model

Revision ID: 9700dbc803df
Revises: 0db6a17730ac
Create Date: 2024-10-17 03:41:43.911869

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9700dbc803df"
down_revision: Union[str, None] = "0db6a17730ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_Products_name", table_name="Products")
    op.drop_column("Products", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Products", sa.Column("name", sa.VARCHAR(), autoincrement=False))
    op.create_index("ix_Products_name", "Products", ["name"], unique=True)
    # ### end Alembic commands ###
