"""Adding username to the user

Revision ID: 7607beae617c
Revises: f5938a854723
Create Date: 2024-09-14 02:18:41.878106

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7607beae617c"
down_revision: Union[str, None] = "f5938a854723"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
