repos:
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        stages: [ pre-commit ]
        files: \.py$
        args:
          - "--in-place"
          - "--max-line-length=88"
          - "--aggressive"
          - "--aggressive"