services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.20
    env_file:
      - path: ./back-end/.env
        required: true
    ports:
      - "5432:5432"
<<<<<<< Updated upstream
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: cheburek_db

    volumes:
      - pgdata:/var/lib/postgresql/data

=======
    volumes:
      - pgdata:/var/lib/postgresql/data
>>>>>>> Stashed changes
  fastapi:
    build: ./back-end
    ports:
      - "8000:8000"
    env_file:
      - path: ./back-end/.env
        required: true
    environment:
<<<<<<< Updated upstream
      POSTGRES_HOST: postgres
    volumes:
      - ./back-end/app:/backend/app
      - ./back-end/alembic:/backend/alembic
      - ./back-end/pyproject.toml:/backend/pyproject.toml
      - ./back-end/poetry.lock:/backend/poetry.lock
      - ./back-end/alembic.ini:/backend/alembic.ini
    depends_on:
      - postgres
      - mongo
=======
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
>>>>>>> Stashed changes

  react:
    build: ./front-end
    container_name: react-container
    ports:
      - '5173:5173'
    volumes:
      - ./front-end/src/:/app/src/
    stdin_open: true
    tty: true
<<<<<<< Updated upstream
    depends_on:
      - fastapi

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=your_username  # Set root username
    #   - MONGO_INITDB_ROOT_PASSWORD=your_password  # Set root password
    #   - MONGO_INITDB_DATABASE=admin               # Set authentication database
    

volumes:
  pgdata:
  mongo-data:
=======

volumes:
  pgdata:
>>>>>>> Stashed changes
