repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest revision
    hooks:
      - id: check-yaml
        stages: [commit]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest version of Flake8
    hooks:
      - id: flake8
        args: ['--exclude=.venv,build,dist, *alembic*', '--max-line-length=120', './backend/']  # Adjust paths as necessary
        # additional_dependencies: [flake8-docstrings]  # Optional, for docstring quality checking
        stages: [commit]
