"""Allow product_id to be nullable in OrderProductAssociation

Revision ID: 87f52eea0b6a
Revises: e3b193e7dfa6
Create Date: 2024-10-28 03:36:19.198763

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87f52eea0b6a"
down_revision: Union[str, None] = "e3b193e7dfa6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_product_association", "product_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint(
        "order_product_association_product_id_fkey",
        "order_product_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "order_product_association",
        "Products",
        ["product_id"],
        ["product_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_product_association", type_="foreignkey")
    op.create_foreign_key(
        "order_product_association_product_id_fkey",
        "order_product_association",
        "Products",
        ["product_id"],
        ["product_id"],
    )
    op.alter_column(
        "order_product_association",
        "product_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    # ### end Alembic commands ###
