"""Add cascade delete to Address.order_id

Revision ID: e3b193e7dfa6
Revises: b2723eb8df99
Create Date: 2024-10-27 06:08:22.565904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3b193e7dfa6"
down_revision: Union[str, None] = "b2723eb8df99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Address_order_id_fkey", "Address", type_="foreignkey")
    op.create_foreign_key(
        None, "Address", "Orders", ["order_id"], ["order_id"], ondelete="CASCADE"
    )
    op.create_unique_constraint(
        "uq_city_name_state_id", "City", ["city_name", "state_id"]
    )
    op.drop_constraint("Orders_order_id_key", "Orders", type_="unique")
    op.drop_constraint("Orders_user_id_key", "Orders", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("Orders_user_id_key", "Orders", ["user_id"])
    op.create_unique_constraint("Orders_order_id_key", "Orders", ["order_id"])
    op.drop_constraint("uq_city_name_state_id", "City", type_="unique")
    op.drop_constraint(None, "Address", type_="foreignkey")
    op.create_foreign_key(
        "Address_order_id_fkey", "Address", "Orders", ["order_id"], ["order_id"]
    )
    # ### end Alembic commands ###
