"""Adding email and status to Order Model

Revision ID: 3b93d7857b8b
Revises: 87f52eea0b6a
Create Date: 2024-10-29 03:24:18.954065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b93d7857b8b"
down_revision: Union[str, None] = "87f52eea0b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Orders", sa.Column("email", sa.String(), nullable=False))
    op.add_column("Orders", sa.Column("status", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Orders", "status")
    op.drop_column("Orders", "email")
    # ### end Alembic commands ###
