"""Updating Product model

Revision ID: 7716217510c9
Revises: 42f13ff5b2aa
Create Date: 2024-10-03 01:56:58.599005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7716217510c9"
down_revision: Union[str, None] = "42f13ff5b2aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Products", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_constraint("Products_name_key", "Products", type_="unique")
    op.create_index(op.f("ix_Products_category"), "Products", ["category"], unique=False)
    op.create_index(op.f("ix_Products_name"), "Products", ["name"], unique=True)
    op.create_index("ix_product_category", "Products", ["category"], unique=False)
    op.create_index("ix_product_price", "Products", ["price"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_product_price", table_name="Products")
    op.drop_index("ix_product_category", table_name="Products")
    op.drop_index(op.f("ix_Products_name"), table_name="Products")
    op.drop_index(op.f("ix_Products_category"), table_name="Products")
    op.create_unique_constraint("Products_name_key", "Products", ["name"])
    op.drop_column("Products", "deleted_at")
    # ### end Alembic commands ###
