"""Creaiting Address and its parents schema

Revision ID: 9ae610eeb24b
Revises: f6ab304328ae
Create Date: 2024-10-26 05:46:34.297541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ae610eeb24b"
down_revision: Union[str, None] = "f6ab304328ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Country",
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.Column("country_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("country_id"),
        sa.UniqueConstraint("country_name"),
    )
    op.create_table(
        "State",
        sa.Column("state_id", sa.Uuid(), nullable=False),
        sa.Column("state_name", sa.String(), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["Country.country_id"],
        ),
        sa.PrimaryKeyConstraint("state_id"),
        sa.UniqueConstraint("state_name"),
    )
    op.create_table(
        "City",
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("country_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["Country.country_id"],
        ),
        sa.PrimaryKeyConstraint("city_id"),
    )
    op.create_table(
        "Address",
        sa.Column("address_id", sa.Uuid(), nullable=False),
        sa.Column("street_name", sa.String(), nullable=False),
        sa.Column("street_number", sa.String(), nullable=False),
        sa.Column("apartment_number", sa.String(), nullable=False),
        sa.Column("zip_code", sa.String(), nullable=False),
        sa.Column("city_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["City.city_id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["Orders.order_id"],
        ),
        sa.PrimaryKeyConstraint("address_id"),
        sa.UniqueConstraint("order_id"),
    )

    op.add_column("Orders", sa.Column("address_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "Orders", ["address_id"])
    op.create_unique_constraint(None, "Orders", ["order_id"])
    op.create_unique_constraint(None, "Orders", ["user_id"])
    op.create_foreign_key(None, "Orders", "Address", ["address_id"], ["address_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Orders", type_="foreignkey")
    op.drop_constraint(None, "Orders", type_="unique")
    op.drop_constraint(None, "Orders", type_="unique")
    op.drop_constraint(None, "Orders", type_="unique")
    op.drop_column("Orders", "address_id")
    op.drop_table("State")
    op.drop_table("City")
    op.drop_table("Country")
    op.drop_table("Address")
    # ### end Alembic commands ###
