"""adding total_count and total_price for Order

Revision ID: 32be34b0cb1b
Revises: 9d3a931b98b2
Create Date: 2024-10-30 05:32:18.108015

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32be34b0cb1b"
down_revision: Union[str, None] = "9d3a931b98b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Orders", sa.Column("total_price", sa.Float(), nullable=False))
    op.add_column("Orders", sa.Column("total_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Orders", "total_count")
    op.drop_column("Orders", "total_price")
    # ### end Alembic commands ###
