"""Fixing relationships

Revision ID: b6f60f612dc9
Revises: da4a87b163cf
Create Date: 2024-10-27 04:36:54.814563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6f60f612dc9"
down_revision: Union[str, None] = "da4a87b163cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("City", sa.Column("state_id", sa.Uuid(), nullable=False))
    op.drop_constraint("City_country_id_fkey", "City", type_="foreignkey")
    op.create_foreign_key(None, "City", "State", ["state_id"], ["state_id"])
    op.drop_column("City", "country_id")
    op.drop_constraint("Orders_address_id_key", "Orders", type_="unique")
    op.drop_constraint("Orders_address_id_fkey", "Orders", type_="foreignkey")
    op.drop_column("Orders", "address_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Orders", sa.Column("address_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "Orders_address_id_fkey", "Orders", "Address", ["address_id"], ["address_id"]
    )
    op.create_unique_constraint("Orders_address_id_key", "Orders", ["address_id"])
    op.add_column(
        "City", sa.Column("country_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "City", type_="foreignkey")
    op.create_foreign_key(
        "City_country_id_fkey", "City", "Country", ["country_id"], ["country_id"]
    )
    op.drop_column("City", "state_id")
    # ### end Alembic commands ###
