"""Adding missing colums

Revision ID: b2723eb8df99
Revises: b6f60f612dc9
Create Date: 2024-10-27 05:38:50.231947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2723eb8df99"
down_revision: Union[str, None] = "b6f60f612dc9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("City", sa.Column("city_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("City", "city_name")
    # ### end Alembic commands ###
