"""Adding Product description fopr translation

Revision ID: e89284e33262
Revises: b4c0e91d4d6d
Create Date: 2024-10-17 20:31:41.959492

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e89284e33262"
down_revision: Union[str, None] = "b4c0e91d4d6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ProductTranslations",
        sa.Column("product_description", sa.String(), nullable=False),
    )
    op.drop_column("Products", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Products",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("ProductTranslations", "product_description")
    # ### end Alembic commands ###
