"""Denormilizing OrderProductAssociation to keep them after product's deletion

Revision ID: 9d3a931b98b2
Revises: 3b93d7857b8b
Create Date: 2024-10-30 04:22:17.783220

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = "9d3a931b98b2"
down_revision: Union[str, None] = "3b93d7857b8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association",
        sa.Column(
            "product_status", sa.String(), nullable=True, server_default="active"
        ),
    )
    op.add_column(
        "order_product_association", sa.Column("name", sa.String(), nullable=True)
    )
    op.add_column(
        "order_product_association", sa.Column("price", sa.Float(), nullable=True)
    )
    op.add_column(
        "order_product_association", sa.Column("category", sa.String(), nullable=True)
    )
    op.add_column(
        "order_product_association", sa.Column("image_src", sa.String(), nullable=True)
    )

    # Temporary table definitions for data migration
    order_product_association = table(
        "order_product_association",
        column("product_id", UUID),
        column("name", sa.String),
        column("price", sa.Float),
        column("category", sa.String),
        column("image_src", sa.String),
    )
    products = table(
        "Products",
        column("product_id", UUID),
        column("price", sa.Float),
        column("category", sa.String),
        column("image_src", sa.String),
    )
    product_translations = table(
        "ProductTranslations",
        column("product_id", UUID),
        column("language_code", sa.String),
        column("product_name", sa.String),
    )

    # Step 2: Populate columns with data from `Products` and `ProductTranslations`
    connection = op.get_bind()
    connection.execute(
        order_product_association.update()
        .values(
            name=product_translations.c.product_name,
            price=products.c.price,
            category=products.c.category,
            image_src=products.c.image_src,
        )
        .where(order_product_association.c.product_id == products.c.product_id)
        .where(
            order_product_association.c.product_id == product_translations.c.product_id,
            product_translations.c.language_code == "en",
        )
    )

    # Step 3: Remove default value from `product_status`
    op.alter_column("order_product_association", "product_status", server_default=None)

    # Step 4: Alter columns to be non-nullable
    op.alter_column("order_product_association", "product_status", nullable=False)
    op.alter_column("order_product_association", "name", nullable=False)
    op.alter_column("order_product_association", "price", nullable=False)
    op.alter_column("order_product_association", "category", nullable=False)
    op.alter_column("order_product_association", "image_src", nullable=False)


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_product_association", "image_src")
    op.drop_column("order_product_association", "category")
    op.drop_column("order_product_association", "price")
    op.drop_column("order_product_association", "name")
    op.drop_column("order_product_association", "product_status")
    # ### end Alembic commands ###
